--- #my playbook
- hosts: dev
  user: ron
  become: yes
  gather_facts: yes
  connection: ssh
  vars:
    pkgname: docker
    index_path: /mnt/sample-deply/

  tasks:
    - name: install docker
      action: yum pkg="{{pkgname}}" state=present
      notify: start service

    - name: deploy index file
      community.docker.docker_compose:
        project_src: /mnt/sample-deply
        files:
        - docker-compose.yml
        scale:
          app: 3

  handlers:
    - name: start service
      action: service name="{{pkgname}}" state=started
